# -----------------------------------------------------------------------------
#  Compiler / Tools
# -----------------------------------------------------------------------------

CXX 		= clang++
LLVM_CONFIG	= llvm-config

CXXFLAGS	= $(shell ${LLVM_CONFIG} --cppflags) \
				-Wall -Wextra -std=c++17 -MMD -MP \
				-DRUNTIME_PATH=\"$(abspath $(RUNTIME_OBJ))\"

LDFLAGS		= $(shell ${LLVM_CONFIG} --ldflags --system-libs --libs all)

BISONFLAGS	= -d

FLEXFLAGS	=

# -----------------------------------------------------------------------------
#  Paths
# -----------------------------------------------------------------------------

EXEC		= vsopc

SRC_DIR		= src

BUILD_DIR	= build

REPORT_DIR	= doc/report

#-----------------------------------------------------------------------------
#  Runtime
#-----------------------------------------------------------------------------

RUNTIME_DIR = $(SRC_DIR)/runtime

RUNTIME_SRC = $(RUNTIME_DIR)/object.c

RUNTIME_OBJ = $(BUILD_DIR)/object.o

# -----------------------------------------------------------------------------
#  Sources
# -----------------------------------------------------------------------------

SRC = 	ast.cpp \
		classes_visitor.cpp \
		codegen_visitor.cpp \
		diagnostics.cpp \
		driver.cpp \
		generation.cpp \
		main.cpp \
		operators.cpp \
		print_visitor.cpp \
		semantics.cpp \
		types.cpp \
		types_visitor.cpp

HEADERS =	ast.hpp \
			colors.hpp \
			diagnostics.hpp \
			driver.hpp \
			generation.hpp \
			llvm_compatibility.hpp \
			mangling.hpp \
			operators.hpp \
			semantics.hpp \
			types.hpp \
			visitors.hpp

# The software (Bison, Flex) generated code.
GENERATED_SRC = parser.cpp lexer.cpp

ALL_SRC = $(SRC) $(GENERATED_SRC)

OBJ = $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(ALL_SRC))

# -----------------------------------------------------------------------------
#  Archiving
#------------------------------------------------------------------------------

ARCHIVE = vsopcompiler.tar.xz

ARCHIVE_FILES = Makefile \
			$(addprefix $(SRC_DIR)/, \
				$(SRC) \
				$(HEADERS) \
				lexer.lex \
				parser.y \
			) \
			$(RUNTIME_DIR)/object.c \
			$(RUNTIME_DIR)/object.h \
			$(REPORT_DIR)/report.pdf

# -----------------------------------------------------------------------------
#  Colors
#------------------------------------------------------------------------------

# ANSI escape sequences. 

C_BLUE		:= "\e[0;34m"
C_GREEN		:= "\e[0;32m"
C_RED		:= "\e[0;31m"
C_LAVANDER	:= "\e[38;5;141m"
C_FUCHSIA	:= "\e[38;5;161m"
C_SALMON	:= "\e[38;5;203m"
C_GOLDEN	:= "\e[38;5;208m"
C_PEACH		:= "\e[38;5;216m"
C_END		:= "\e[0m"

# -----------------------------------------------------------------------------
#  Main targets
# -----------------------------------------------------------------------------

all: $(EXEC)

# Link the object files.
$(EXEC): $(OBJ) $(RUNTIME_OBJ)
	@echo -e $(C_GOLDEN)"Linking:   "$(C_END) $@;
	@$(CXX) -o $@ $(OBJ) $(RUNTIME_OBJ) $(LDFLAGS)

# Compile each .cpp file to .o file.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	@echo -e $(C_LAVANDER)"Compiling: "$(C_END) $@;
	@$(CXX) $(CXXFLAGS) -c $< -o $@

# Create build directory if missing.
$(BUILD_DIR):
	@echo -e $(C_GREEN)"Creating build directory..."$(C_END);
	@mkdir -p $(BUILD_DIR)

# Generate parser with Bison.
$(SRC_DIR)/parser.cpp $(SRC_DIR)/parser.hpp: $(SRC_DIR)/parser.y
	@echo -e $(C_PEACH)"Bison:     "$(C_END) $@;
	@bison $(BISONFLAGS) -o $(SRC_DIR)/parser.cpp $^

# Generate lexer with Flex.
$(SRC_DIR)/lexer.cpp: $(SRC_DIR)/lexer.lex
	@echo -e $(C_PEACH)"Flex:      "$(C_END) $@;
	@flex $(FLEXFLAGS) -o $(SRC_DIR)/lexer.cpp $^

# Ensure parser and lexer are generated before any compilation
$(OBJ): $(SRC_DIR)/parser.hpp $(SRC_DIR)/lexer.cpp

# Compile the runtime to an object file.
$(RUNTIME_OBJ): $(RUNTIME_SRC) | $(BUILD_DIR)
	@echo -e $(C_PEACH)"Runtime:   "$(C_END) $@;
	@clang -c $< -o $@

# -----------------------------------------------------------------------------
#  Utility targets
# -----------------------------------------------------------------------------

# Add a root directory called vscompiler in the archive
archive: $(ARCHIVE_FILES)
	@echo -e $(C_GREEN)"Creating archive..."$(C_END);
	@tar -cJf $(ARCHIVE) --transform='s,^,vsopcompiler/,' $^

install-tools:
	@:

clean:
	@rm -f $(EXEC)
	@rm -rf $(BUILD_DIR)
	@rm -f	$(SRC_DIR)/lexer.cpp \
			$(SRC_DIR)/parser.cpp \
			$(SRC_DIR)/parser.hpp \
			$(SRC_DIR)/location.hh
	@rm -f $(ARCHIVE)

# Target specific variable assignment for debugging.
# All compiled code will be compiled with the DEBUG variable and debug symbols.
# Using gdward-4 for backward compatibility with the Container test environment.
debug: CXXFLAGS += -DDEBUG -g -gdwarf-4

debug: LDFLAGS += -v

debug: print_debug $(EXEC)

print_debug:
	@echo -e $(C_RED)"Compiling in DEBUG mode."$(C_END);

doc:
	doxygen Doxyfile

.PHONY: all clean install-tools archive debug doc

# Look for dependencies files generated by the compiler in build directory.
-include $(OBJ:.o=.d)
