# -----------------------------------------------------------------------------
#  Compiler / Tools
# -----------------------------------------------------------------------------

CXX 		= clang++
LLVM_CONFIG	= llvm-config

CXXFLAGS    = $(shell ${LLVM_CONFIG} --cppflags) -Wall -Wextra -g -std=c++17 -gdwarf-4 -MMD -MP

LDFLAGS	    = $(shell ${LLVM_CONFIG} --ldflags --system-libs --libs all)

BISONFLAGS = -d

FLEXFLAGS  =

# -----------------------------------------------------------------------------
#  Paths
# -----------------------------------------------------------------------------

EXEC       = vsopc

SRC_DIR    = src

BUILD_DIR  = build

ARCHIVE    = vsopcompiler.tar.xz

# -----------------------------------------------------------------------------
#  Sources
# -----------------------------------------------------------------------------

SRC = 	ast.cpp \
		classes_visitor.cpp \
		codegen_visitor.cpp \
		driver.cpp \
		main.cpp \
		print_visitor.cpp \
		semantics.cpp \
		types_visitor.cpp

HEADERS =	ast.hpp \
			colors.hpp \
			driver.hpp \
			generation.hpp \
			semantics.hpp \
			visitors.hpp

GENERATED_SRC = parser.cpp lexer.cpp

ALL_SRC = $(SRC) $(GENERATED_SRC)

OBJ = $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(ALL_SRC))

# -----------------------------------------------------------------------------
#  Archive
#-----------------------------------------------------------------------------

ARCHIVE_FILES = Makefile \
			$(addprefix $(SRC_DIR)/, \
				$(SRC) \
				$(HEADERS) \
				lexer.lex \
				parser.y \
			)

# -----------------------------------------------------------------------------
#  Colors
#-----------------------------------------------------------------------------

# ANSI escape sequences. 

C_BLUE    	:= "\e[0;34m"
C_GREEN     := "\e[0;32m"
C_RED    	:= "\e[0;31m"
C_LAVANDER  := "\e[38;5;141m"
C_FUCHSIA   := "\e[38;5;161m"
C_SALMON    := "\e[38;5;203m"
C_GOLDEN	:= "\e[38;5;208m"
C_PEACH     := "\e[38;5;216m"
C_END 		:= "\e[0m"

# -----------------------------------------------------------------------------
#  Main targets
# -----------------------------------------------------------------------------

all: $(EXEC)

# Link the object files.
$(EXEC): $(OBJ)
	@echo -e $(C_GOLDEN)"Linking:   "$(C_END) $@;
	@$(CXX) -o $@ $(OBJ) $(LDFLAGS)

# Compile each .cpp file to .o file.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	@echo -e $(C_LAVANDER)"Compiling: "$(C_END) $@;
	@$(CXX) $(CXXFLAGS) -c $< -o $@

# Create build directory if missing.
$(BUILD_DIR):
	@echo -e $(C_GREEN)"Creating build directory..."$(C_END);
	@mkdir -p $(BUILD_DIR)

# Generate parser with Bison.
$(SRC_DIR)/parser.cpp $(SRC_DIR)/parser.hpp: $(SRC_DIR)/parser.y
	@echo -e $(C_PEACH)"Bison:     "$(C_END) $@;
	@bison $(BISONFLAGS) -o $(SRC_DIR)/parser.cpp $^

# Generate lexer with Flex.
$(SRC_DIR)/lexer.cpp: $(SRC_DIR)/lexer.lex
	@echo -e $(C_PEACH)"Flex:      "$(C_END) $@;
	@flex $(FLEXFLAGS) -o $(SRC_DIR)/lexer.cpp $^

# Ensure parser and lexer are generated before any compilation
$(OBJ): $(SRC_DIR)/parser.hpp $(SRC_DIR)/lexer.cpp

# -----------------------------------------------------------------------------
#  Utility targets
# -----------------------------------------------------------------------------

# Add a root directory called vscompiler in the archive
archive: $(ARCHIVE_FILES)
	@echo -e $(C_GREEN)"Creating archive..."$(C_END);
	@tar -cJf $(ARCHIVE) --transform='s,^,vsopcompiler/,' $^

install-tools:
	@:

clean:
	@rm -f $(EXEC)
	@rm -rf $(BUILD_DIR)
	@rm -f \
		$(SRC_DIR)/lexer.cpp \
		$(SRC_DIR)/parser.cpp \
		$(SRC_DIR)/parser.hpp \
		$(SRC_DIR)/location.hh
	@rm -f $(ARCHIVE)

# Target specific variable assignment for debugging
debug: CXXFLAGS += -DDEBUG

debug: print_debug $(EXEC)

print_debug:
	@echo -e $(C_RED)"Compiling in DEBUG mode."$(C_END);

.PHONY: all clean install-tools archive debug

# Look for dependencies files generated by the compiler in build directory.
-include $(OBJ:.o=.d)